version: '3.5'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.4-latest
    depends_on:
      - db
    environment:
      DB_SERVER_HOST: db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
    ports:
      - "10051:10051"

  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.4-latest
    depends_on:
      - db
      - zabbix-server
    environment:
      DB_SERVER_HOST: db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: UTC
    ports:
      - "8080:8080"
