version: '3.5'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
    ports:
      - "5432:5432"

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-7.2-latest
    depends_on:
      - db
    environment:
      DB_SERVER_HOST: db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
      POSTGRES_DB: zabbix
    ports:
      - "10052:10051"

  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.2-latest
    depends_on:
      - db
      - zabbix-server
    environment:
      DB_SERVER_HOST: db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: UTC
    ports:
      - "8282:8080"
