name: Zabbix API Integration Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Spin up Zabbix containers
        run: |
          docker-compose -f ./docker/docker-compose-testing.yml up -d

      - name: Wait for Zabbix Frontend (API)
        run: |
          echo "Waiting for Zabbix API (Frontend)..."
          until curl -s http://localhost:8080/api_jsonrpc.php | grep -q "Parse error"; do
            echo -n "."
            sleep 5
          done
          echo "Zabbix Frontend is up!"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.3'

      - name: Run Go integration tests
        run: go test ./... -v
